# Nome da aplicação
spring.application.name=demo
server.port=8091

# Expor todos os endpoints do actuator
management.endpoints.web.exposure.include=*

# (Opcional) Prefixo dos endpoints do actuator
management.endpoints.web.base-path=/actuator

